ci:
  - changed-files:
      - any-glob-to-any-file:
          - .github/workflows/**

documentation:
  - changed-files:
      - any-glob-to-any-file:
          - docs/config/zh-CN.json
          - docs/zh-CN/**

core:
  - changed-files:
      - any-glob-to-any-file: packages/core/**

# Sources
'source: danbooru':
  - changed-files:
      - any-glob-to-any-file: packages/danbooru/**
'source: e621':
  - changed-files:
      - any-glob-to-any-file: packages/e621/**
'source: gelbooru':
  - changed-files:
      - any-glob-to-any-file: packages/gelbooru/**
'source: konachan':
  - changed-files:
      - any-glob-to-any-file: packages/konachan/**
'source: local':
  - changed-files:
      - any-glob-to-any-file: packages/local/**
'source: lolibooru':
  - changed-files:
      - any-glob-to-any-file: packages/lolibooru/**
'source: lolicon':
  - changed-files:
      - any-glob-to-any-file: packages/lolicon/**
'source: moehu':
  - changed-files:
      - any-glob-to-any-file: packages/moehu/**
'source: pixiv':
  - changed-files:
      - any-glob-to-any-file: packages/pixiv/**
'source: safebooru':
  - changed-files:
      - any-glob-to-any-file: packages/safebooru/**
'source: sankaku':
  - changed-files:
      - any-glob-to-any-file: packages/sankaku/**
'source: yandere':
  - changed-files:
      - any-glob-to-any-file: packages/yande/**
