name: Comment on Pull Requests

on:
  workflow_run:
    workflows:
      - Build
    types:
      - completed

jobs:
  upload:
    permissions:
      contents: read
      pull-requests: write
    concurrency:
      group: booru-${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true
    uses: cordiverse/workflows/.github/workflows/post-comment.yml@main
